# NumPy Basics Tutorial

In [1]:
import numpy as np
import sys

#https://www.youtube.com/watch?v=QUT1VHiLmmI
#Left off at: 0:18:30

#NumPy is a multidimensional array library
# Store all sorts of data in 1D, 2D, 3D, 4D... arrays
#Why is NumPy over lists
# lists are slow, whilst NumPy is fast
# NumPy uses fixed types

#NumPy
# int8 = 1 byte, int16 = 2 bytes, int32 = 4 bytes
#Lists (bascially require a lot more space)
# Size
# Reference Count
# Object Type
# Object Value

#NumPy (contiguous memory)
# Imagine all the elements of the list being next to each other in memory as opposed to the pointer strucutre in lists
# SIMD (single instruction multiple data) Vector Processing
# Effective cache utilization

#DIFFERENCES
# NumPy
#  Insertion, Deletion, Appending, Concatenation etc.
#  LOTS More
# Lists
#  Insertion, Deletion, Appending, Concatenation etc.

## The Basics

In [14]:
#A 1D array
a = np.array([1, 2, 3], dtype = "int8")
b = np.array([4, 5, 6], dtype = "int8")


#A 2D array
c = np.array([[10, 11, 12], [13, 14, 15]], dtype = "int8")


#Print Matrix
print("Matrix a:", a, "Matrix b:", b)
print("Matrix c: \n", c)

#Get Dimensions
print("Matrix a dimensions:", a.ndim, "Matrix b dimensions:", b.ndim)
print("Matrix c dimensions:", c.ndim)

#Get Shape
print("Matrix a shape (r,c):", a.shape, "Matrix b shape (r,c):", b.shape)
print("Matrix c shape (r,c):", c.shape)


#Get Type
print("Matrix a type:", a.dtype, "Matrix b type:", b.dtype)
print("Matrix c dtype:", c.dtype)

#Get Size or Total Size
print("Matrix a size (bytes):", a.itemsize, "Matrix b total size:", b.size * b.itemsize)
print("Matrix c nbytes:", c.nbytes)

Matrix a: [1 2 3] Matrix b: [4 5 6]
Matrix c: 
 [[10 11 12]
 [13 14 15]]
Matrix a dimensions: 1 Matrix b dimensions: 1
Matrix c dimensions: 2
Matrix a shape (r,c): (3,) Matrix b shape (r,c): (3,)
Matrix c shape (r,c): (2, 3)
Matrix a type: int8 Matrix b type: int8
Matrix c dtype: int8
Matrix a size (bytes): 1 Matrix b total size: 3
Matrix c nbytes: 6


## Accessing/Changing Specific Elements, Rows, Columns, etc

In [25]:
d = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print("Array d: \n", d, "\nShape of array d (r,c): \n", d.shape)

Array d: 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] 
Shape of array d (r,c): 
 (2, 7)


In [28]:
#Get a specific element [row, column] or [r, c]

# Get the number 13 from array d
print(d[1, 5])

# Get a specific column
print(d[1, :])

# Get a specific row
print(d[:, 1])


13
[ 8  9 10 11 12 13 14]
[2 9]


## Initializing Different Types of Arrays

## Mathematics

## Reorganizing Arrays

## Miscellaneous